/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoif;

import AppPackage.AnimationClass;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {
    DB db;
    DBCollection collection;
    /**
     * Creates new form login
     */
    public login() {
        try{
            Mongo mongo = new Mongo();
            db=mongo.getDB("ifsp");
            collection = db.getCollection("objetos");
        } catch(Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_ingresso = new javax.swing.JPanel();
        txt_senha = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        field_usuario = new javax.swing.JTextField();
        separador_senha = new javax.swing.JSeparator();
        separador_usuario = new javax.swing.JSeparator();
        field_senha = new javax.swing.JPasswordField();
        icon_list = new javax.swing.JLabel();
        icon_usuario = new javax.swing.JLabel();
        icon_senha = new javax.swing.JLabel();
        btn_enter = new javax.swing.JButton();
        icon_cadastrar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        icon_minimizar = new javax.swing.JLabel();
        icon_fechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_ingresso.setBackground(new java.awt.Color(51, 51, 51));
        jp_ingresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jp_ingresso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_senha.setBackground(new java.awt.Color(194, 194, 194));
        txt_senha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_senha.setForeground(new java.awt.Color(194, 194, 194));
        txt_senha.setText("Senha");
        jp_ingresso.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txt_usuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(194, 194, 194));
        txt_usuario.setText("Usuário");
        jp_ingresso.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usericon.png"))); // NOI18N
        jp_ingresso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 210, 190));

        field_usuario.setBackground(new java.awt.Color(51, 51, 51));
        field_usuario.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        field_usuario.setForeground(new java.awt.Color(194, 194, 194));
        field_usuario.setText("Digite o usuário");
        field_usuario.setBorder(null);
        field_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usuarioActionPerformed(evt);
            }
        });
        jp_ingresso.add(field_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 40));
        jp_ingresso.add(separador_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 20));
        jp_ingresso.add(separador_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 20));

        field_senha.setBackground(new java.awt.Color(51, 51, 51));
        field_senha.setForeground(new java.awt.Color(153, 153, 153));
        field_senha.setText("***************");
        field_senha.setBorder(null);
        jp_ingresso.add(field_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 40));

        icon_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-three-horizontal-lines-symbol.png"))); // NOI18N
        jp_ingresso.add(icon_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        icon_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-silhouette.png"))); // NOI18N
        jp_ingresso.add(icon_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 30));

        icon_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key.png"))); // NOI18N
        jp_ingresso.add(icon_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btn_enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_entrar2.jpg"))); // NOI18N
        btn_enter.setBorder(null);
        btn_enter.setBorderPainted(false);
        btn_enter.setContentAreaFilled(false);
        btn_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_entrar1.jpg"))); // NOI18N
        btn_enter.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_entrar1.jpg"))); // NOI18N
        btn_enter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_entrar1.jpg"))); // NOI18N
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        jp_ingresso.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 130, 40));

        icon_cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        icon_cadastrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        icon_cadastrar.setForeground(new java.awt.Color(194, 194, 194));
        icon_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_cadastrar.setText("Ainda não tem um usuário? Cadastre-se");
        icon_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_ingresso.add(icon_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 260, -1));

        getContentPane().add(jp_ingresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Maintenance_96px.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 190, 170));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Today_96px.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 190, 170));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Clock_96px.png"))); // NOI18N
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 190, 170));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Idea_96px.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel5MouseMoved(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, 170));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Google_Drive_96px.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel6MouseMoved(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 190, 170));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Handshake_96px.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel7MouseMoved(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 190, 170));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 99, 71));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Calendario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 170, 70, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 99, 71));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Horario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 170, 60, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ferramentas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 170, 90, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ideia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 70, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Google Drive");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 390, 90, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Hand Shake");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 760, 520));

        jPanel2.setBackground(new java.awt.Color(26, 26, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Expand_Arrow_32px.png"))); // NOI18N
        icon_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_minimizarMouseClicked(evt);
            }
        });
        jPanel2.add(icon_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        icon_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Multiply_32px.png"))); // NOI18N
        icon_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_fecharMouseClicked(evt);
            }
        });
        jPanel2.add(icon_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usuarioActionPerformed

    private void icon_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_fecharMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Deseja sair do Login", "Sair", dialog);
        
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_icon_fecharMouseClicked

    private void icon_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_minimizarMouseClicked
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_icon_minimizarMouseClicked

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseMoved
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel5MouseMoved

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseMoved
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel6MouseMoved

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26,26,26)));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseMoved
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jLabel7MouseMoved

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        String usuario = field_usuario.getText();
        String senha = field_senha.getText();   
        
        if(usuario.isEmpty() == true || senha.isEmpty() == true){
           
           JOptionPane.showMessageDialog(new JFrame(), "Usuario ou senha estão vazios!");
           
        }
    }//GEN-LAST:event_btn_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enter;
    private javax.swing.JPasswordField field_senha;
    private javax.swing.JTextField field_usuario;
    private javax.swing.JLabel icon_cadastrar;
    private javax.swing.JLabel icon_fechar;
    private javax.swing.JLabel icon_list;
    private javax.swing.JLabel icon_minimizar;
    private javax.swing.JLabel icon_senha;
    private javax.swing.JLabel icon_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp_ingresso;
    private javax.swing.JSeparator separador_senha;
    private javax.swing.JSeparator separador_usuario;
    private javax.swing.JLabel txt_senha;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
